WOOD_PICKAXE: 'pcempty'
WOOD_PICKAXE_PERMS: 'pcwood'
STONE_PICKAXE: 'pcempty'
STONE_PICKAXE_PERMS: 'pcstone'
IRON_PICKAXE: 'pcempty'
IRON_PICKAXE_PERMS: 'pciron'
GOLD_PICKAXE: 'pcempty'
GOLD_PICKAXE_PERMS: 'pcgold'
DIAMOND_PICKAXE: 'pcempty'
DIAMOND_PICKAXE_PERMS: 'pcdiamond'