## 
## For tool and item names, please use the enumeration names as defined in the library
## XSeries with the XMaterial enum.  This ensures compatibility with Spigot 1.8 through 1.17.x.
## 
## You can find reference to XMaterial on github:
##   https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XMaterial.java
## 
## The command must be a command that is runnable from the console.  IF it cannot be ran from the console,
## then it will not work here.  All commands are ran as bukkit's CommandSender, which is the same as 
## running it as OP.
##
## There is an alternative to using the CommandSender to run these commands, and that is running the 
## command as the player. This option is possile if using the placeholder '{runAsPlayer}'. This 
## placeholder can be placed anywhere within the command since it will be removed prior to running 
## the command. If you are using this placeholder, then it must be specified on each tool's command
## set.
## 
## You can use the placeholder '{player}' to insert the player's name in the command. 
## 
## Placeholders can use either { } or % % as escape characters.  Either works well.
## 
## 
## The permissions must be a plain permissions if used. It cannot be a group permission. 
## If permissions are not to be used, then make it an empty String value.  Use '' and not ' '.
## 
## 
## 


WOODEN_PICKAXE: ''
WOODEN_PICKAXE_PERMS: 'pc.pickaxe.wooden'
STONE_PICKAXE: ''
STONE_PICKAXE_PERMS: 'pc.pickaxe.stone'
IRON_PICKAXE: ''
IRON_PICKAXE_PERMS: 'pc.pickaxe.iron'
GOLDEN_PICKAXE: ''
GOLDEN_PICKAXE_PERMS: 'pc.pickaxe.golden'
DIAMOND_PICKAXE: ''
DIAMOND_PICKAXE_PERMS: 'pc.pickaxe.diamond'
NETHERITE_PICKAXE: ''
NETHERITE_PICKAXE_PERMS: 'pc.pickaxe.netherite'
        
WOODEN_SHOVEL: ''
WOODEN_SHOVEL_PERMS: 'pc.shovel.wooden'
STONE_SHOVEL: ''
STONE_SHOVEL_PERMS: 'pc.pickaxe.stone'
IRON_SHOVEL: ''
IRON_SHOVEL_PERMS: 'pc.pickaxe.iron'
GOLDEN_SHOVEL: ''
GOLDEN_SHOVEL_PERMS: 'pc.pickaxe.golden'
DIAMOND_SHOVEL: ''
DIAMOND_SHOVEL_PERMS: 'pc.pickaxe.diamond'
NETHERITE_SHOVEL: ''
NETHERITE_SHOVEL_PERMS: 'pc.pickaxe.netherite'


BOW: ''
BOW_PERMS: 'pc.bow'
CROSSBOW: ''
CROSSBOW_PERMS: 'pc.crossbow'
TRIDENT:  ''
TRIDENT_PERMS: 'pc.trident'
STICK:  ''
STICK_PERMS: 'pc.stick'
BLAZE_ROD:  ''
BLAZE_ROD_PERMS:  'pc.blazerod'


WOODEN_AXE: ''
WOODEN_AXE_PERMS: 'pc.axe.wooden'
STONE_AXE: ''
STONE_AXE_PERMS: 'pc.axe.stone'
IRON_AXE: ''
IRON_AXE_PERMS: 'pc.axe.iron'
GOLDEN_AXE: ''
GOLDEN_AXE_PERMS: 'pc.axe.golden'
DIAMOND_AXE: ''
DIAMOND_AXE_PERMS: 'pc.axe.diamond'
NETHERITE_AXE: ''
NETHERITE_AXE_PERMS: 'pc.axe.netherite'

WOODEN_SWORD: ''
WOODEN_SWORD_PERMS: 'pc.sword.wooden'
STONE_SWORD: ''
STONE_SWORD_PERMS: 'pc.sword.stone'
IRON_SWORD: ''
IRON_SWORD_PERMS: 'pc.sword.iron'
GOLDEN_SWORD: ''
GOLDEN_SWORD_PERMS: 'pc.sword.golden'
DIAMOND_SWORD: ''
DIAMOND_SWORD_PERMS: 'pc.sword.diamond'
NETHERITE_SWORD: ''
NETHERITE_SWORD_PERMS: 'pc.sword.netherite'
        
WOODEN_HOE: ''
WOODEN_HOE_PERMS: 'pc.hoe.wooden'
STONE_HOE: ''
STONE_HOE_PERMS: 'pc.hoe.stone'
IRON_HOE: ''
IRON_HOE_PERMS: 'pc.hoe.iron'
GOLDEN_HOE: ''
GOLDEN_HOE_PERMS: 'pc.hoe.golden'
DIAMOND_HOE: ''
DIAMOND_HOE_PERMS: 'pc.hoe.diamond'
NETHERITE_HOE: ''
NETHERITE_HOE_PERMS: 'pc.hoe.netherite'

