## 
## For tool and item names, please use the enumeration names as defined in the library
## XSeries with the XMaterial enum.  This ensures compatibility with Spigot 1.8 through 1.17.x.
## 
## You can find reference to XMaterial on github:
##   https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XMaterial.java
## 
## The command must be a command that is runnable from the console.  IF it cannot be ran from the console,
## then it will not work here.  All commands are ran as bukkit's CommandSender, which is the same as 
## running it as OP.
##
## There is an alternative to using the CommandSender to run these commands, and that is running the 
## command as the player. This option is possile if using the placeholder '{runAsPlayer}'. This 
## placeholder can be placed anywhere within the command since it will be removed prior to running 
## the command. If you are using this placeholder, then it must be specified on each command, or 
## sub command, where it needs to be used.
## 
## You can use the placeholder '{player}' to insert the player's name in the command. 
## 
## Placeholders can use either { } or % % as escape characters.  Either works well.
## 
## 
## The permissions must be a plain permissions if used. It cannot be a group permission. 
## If permissions are not to be used, then make it an empty String value.  Use '' and not ' '.
## 
## More than one command can be included in each item.  Use a ';' to seperate each command.
## All commands must be within the same quoted text.  If you need to use '{runAsPlayer]' 
## in more than one command, then it must be specified in each occurance. There technically
## are no limitation on the number of commands you can include.
##
## Please note that if sub-commands are used, they will be submitted to run back-to-back, 
## but there are no guarantees that they will be executed in the same order. There is also
## a good chance that one or more of the commands may also resubmit their command to run
## in the near future.  So do not expect that all these commands will run, or complete 
## in any specific order.
##
## Example using multiple sub-commands in one item command. One of the sub-commands is using
## the '{runAsPlayer}' placeholder:
## DIAMOND_PICKAXE: 'eco give {player} 1000;broadcast Hey!! {player} just got 1000!!;{runAsPlayer}balance {player};eco take {player} 1000;broadcast oof!! {player} just lost 1000. Too bad!'
## 
## 


WOODEN_PICKAXE: ''
WOODEN_PICKAXE_PERMS: 'pc.pickaxe.wooden'
STONE_PICKAXE: ''
STONE_PICKAXE_PERMS: 'pc.pickaxe.stone'
IRON_PICKAXE: ''
IRON_PICKAXE_PERMS: 'pc.pickaxe.iron'
GOLDEN_PICKAXE: ''
GOLDEN_PICKAXE_PERMS: 'pc.pickaxe.golden'
DIAMOND_PICKAXE: ''
DIAMOND_PICKAXE_PERMS: 'pc.pickaxe.diamond'
NETHERITE_PICKAXE: ''
NETHERITE_PICKAXE_PERMS: 'pc.pickaxe.netherite'
        
WOODEN_SHOVEL: ''
WOODEN_SHOVEL_PERMS: 'pc.shovel.wooden'
STONE_SHOVEL: ''
STONE_SHOVEL_PERMS: 'pc.pickaxe.stone'
IRON_SHOVEL: ''
IRON_SHOVEL_PERMS: 'pc.pickaxe.iron'
GOLDEN_SHOVEL: ''
GOLDEN_SHOVEL_PERMS: 'pc.pickaxe.golden'
DIAMOND_SHOVEL: ''
DIAMOND_SHOVEL_PERMS: 'pc.pickaxe.diamond'
NETHERITE_SHOVEL: ''
NETHERITE_SHOVEL_PERMS: 'pc.pickaxe.netherite'


BOW: ''
BOW_PERMS: 'pc.bow'
CROSSBOW: ''
CROSSBOW_PERMS: 'pc.crossbow'
TRIDENT:  ''
TRIDENT_PERMS: 'pc.trident'
STICK:  ''
STICK_PERMS: 'pc.stick'
BLAZE_ROD:  ''
BLAZE_ROD_PERMS:  'pc.blazerod'


WOODEN_AXE: ''
WOODEN_AXE_PERMS: 'pc.axe.wooden'
STONE_AXE: ''
STONE_AXE_PERMS: 'pc.axe.stone'
IRON_AXE: ''
IRON_AXE_PERMS: 'pc.axe.iron'
GOLDEN_AXE: ''
GOLDEN_AXE_PERMS: 'pc.axe.golden'
DIAMOND_AXE: ''
DIAMOND_AXE_PERMS: 'pc.axe.diamond'
NETHERITE_AXE: ''
NETHERITE_AXE_PERMS: 'pc.axe.netherite'

WOODEN_SWORD: ''
WOODEN_SWORD_PERMS: 'pc.sword.wooden'
STONE_SWORD: ''
STONE_SWORD_PERMS: 'pc.sword.stone'
IRON_SWORD: ''
IRON_SWORD_PERMS: 'pc.sword.iron'
GOLDEN_SWORD: ''
GOLDEN_SWORD_PERMS: 'pc.sword.golden'
DIAMOND_SWORD: ''
DIAMOND_SWORD_PERMS: 'pc.sword.diamond'
NETHERITE_SWORD: ''
NETHERITE_SWORD_PERMS: 'pc.sword.netherite'
        
WOODEN_HOE: ''
WOODEN_HOE_PERMS: 'pc.hoe.wooden'
STONE_HOE: ''
STONE_HOE_PERMS: 'pc.hoe.stone'
IRON_HOE: ''
IRON_HOE_PERMS: 'pc.hoe.iron'
GOLDEN_HOE: ''
GOLDEN_HOE_PERMS: 'pc.hoe.golden'
DIAMOND_HOE: ''
DIAMOND_HOE_PERMS: 'pc.hoe.diamond'
NETHERITE_HOE: ''
NETHERITE_HOE_PERMS: 'pc.hoe.netherite'


     
LEATHER_HELMET: ''
LEATHER_HELMET_PERMS: 'pc.helmet.leather'
CHAINMAIL_HELMET: ''
CHAINMAIL_HELMET_PERMS: 'pc.helmet.chainmail'
IRON_HELMET: ''
IRON_HELMET_PERMS: 'pc.helmet.iron'
GOLDEN_HELMET: ''
GOLDEN_HELMET_PERMS: 'pc.helmet.golden'
DIAMOND_HELMET: ''
DIAMOND_HELMET_PERMS: 'pc.helmet.diamond'
NETHERITE_HELMET: ''
NETHERITE_HELMET_PERMS: 'pc.helmet.netherite'
TURTLE_HELMET: ''
TURTLE_HELMET_PERMS: 'pc.helmet.turtle'
        
LEATHER_CHESTPLATE: ''
LEATHER_CHESTPLATE_PERMS: 'pc.chestplate.leather'
CHAINMAIL_CHESTPLATE: ''
CHAINMAIL_CHESTPLATE_PERMS: 'pc.chestplate.chainmail'
IRON_CHESTPLATE: ''
IRON_CHESTPLATE_PERMS: 'pc.chestplate.iron'
GOLDEN_CHESTPLATE: ''
GOLDEN_CHESTPLATE_PERMS: 'pc.chestplate.golden'
DIAMOND_CHESTPLATE: ''
DIAMOND_CHESTPLATE_PERMS: 'pc.chestplate.diamond'
NETHERITE_CHESTPLATE: ''
NETHERITE_CHESTPLATE_PERMS: 'pc.chestplate.netherite'
        
LEATHER_LEGGINGS: ''
LEATHER_LEGGINGS_PERMS: 'pc.leggings.leather'
CHAINMAIL_LEGGINGS: ''
CHAINMAIL_LEGGINGS_PERMS: 'pc.leggings.chainmail'
IRON_LEGGINGS: ''
IRON_LEGGINGS_PERMS: 'pc.leggings.iron'
GOLDEN_LEGGINGS: ''
GOLDEN_LEGGINGS_PERMS: 'pc.leggings.golden'
DIAMOND_LEGGINGS: ''
DIAMOND_LEGGINGS_PERMS: 'pc.leggings.diamond'
NETHERITE_LEGGINGS: ''
NETHERITE_LEGGINGS_PERMS: 'pc.leggings.netherite'

LEATHER_BOOTS: ''
LEATHER_BOOTS_PERMS: 'pc.boots.leather'
CHAINMAIL_BOOTS: ''
CHAINMAIL_BOOTS_PERMS: 'pc.boots.chainmail'
IRON_BOOTS: ''
IRON_BOOTS_PERMS: 'pc.boots.iron'
GOLDEN_BOOTS: ''
GOLDEN_BOOTS_PERMS: 'pc.boots.golden'
DIAMOND_BOOTS: ''
DIAMOND_BOOTS_PERMS: 'pc.boots.diamond'
NETHERITE_BOOTS: ''
NETHERITE_BOOTS_PERMS: 'pc.boots.netherite'


