name: PickaxeCommands
main: com.r1ckp1ckle.pickaxecommands.PickaxeCommandsCore
version: "${version}"
author: r1ckp1ckle, RoyalBlueRanger

# Older versions than 1.13 will ignore this, but this will allow 1.13 and up to use newer block types?
api-version: 1.13

commands:
  pcempty:
    usage: /<command>
    description: Does nothing. Is a template for the PickaxeCommands plugin.
    permission: pc.admin
  pcreload:
    usage: /<command>
    description: reloads the config file settings
    permission: pc.admin